### PR TITLE
Support for new emulator debugger

### PR DESCRIPTION
**Pull request by bluesign**
## Description

Adds support for debugging server in next emulator. 

______

For contributor use:

- [X] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [X] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [X] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
Debugging support was just merged into the Emulator: onflow/flow-emulator#294. 

It would be nice to get a release out for it, and then merge this PR and do a release.

**Comment by DylanTinianov** [comment]
Thanks @bluesign, I will do some testing on this with newest emulator and then review soon!

**Comment by sideninja** [comment]
@bluesign do you have something else to do on this PR or ready for review? in that case @DylanTinianov please take time today to review it

**Comment by bluesign** [comment]
@sideninja it should be ready to review

**Review by DylanTinianov — APPROVED** [review]

**Pull request merged**
